trigger:
  - main

pool:
  name: mi-selfhost
  demands:
    - agent.name -equals mi-agent

stages:
  - stage: Build
    jobs:
      - job: frontend_build
        displayName: 'Build Frontend'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'
            displayName: 'Install Node.js'

          # Remove Azure Artifacts .npmrc and create new one for public registry
          - script: |
              cd frontend
              rm -f .npmrc
              echo "registry=https://registry.npmjs.org/" > .npmrc
            displayName: 'Configure npm Registry'

          # Clean npm cache
          - script: |
              npm cache clean --force
            displayName: 'Clean npm Cache'
            continueOnError: true

          # Install frontend dependencies
          - script: |
              cd frontend
              npm install --loglevel=error --fetch-timeout=600000 --fetch-retries=5
            displayName: 'Install Frontend Dependencies'
            timeoutInMinutes: 15

          # Build frontend
          - script: |
              cd frontend
              npm run build
            displayName: 'Build Frontend'
            timeoutInMinutes: 10

      - job: backend_build
        displayName: 'Build Backend'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'
            displayName: 'Install Node.js'

          # Remove Azure Artifacts .npmrc and create new one for public registry
          - script: |
              cd backend
              rm -f .npmrc
              echo "registry=https://registry.npmjs.org/" > .npmrc
            displayName: 'Configure npm Registry'

          # Clean npm cache
          - script: |
              npm cache clean --force
            displayName: 'Clean npm Cache'
            continueOnError: true

          # Install backend dependencies
          - script: |
              cd backend
              npm install --loglevel=error --fetch-timeout=600000 --fetch-retries=5
            displayName: 'Install Backend Dependencies'
            timeoutInMinutes: 15

          # Build backend
          - script: |
              cd backend
              npm run build
            displayName: 'Build Backend'
            timeoutInMinutes: 10

# Trivy scan stages
  - stage: Trivy_FS_Scan
    displayName: 'Trivy FS Scan Frontend & Backend'
    dependsOn: Build
    jobs:
      - job: trivy_fs_scan_frontend
        displayName: 'Trivy FS Scan Frontend'
        steps:
          - script: |
              cd frontend
              trivy fs --format table -o trivy-frontend.html .
            displayName: 'Trivy Scan Frontend'
          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: 'frontend-report'
              targetPath: 'frontend/trivy-frontend.html'

      - job: trivy_fs_scan_backend
        displayName: 'Trivy FS Scan Backend'
        steps:
          - script: |
              cd backend
              trivy fs --format table -o trivy-backend.html .
            displayName: 'Trivy Scan Backend'
          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: 'backend-report'
              targetPath: 'backend/trivy-backend.html'

# SonarQube stages
  - stage: SonarQube_Frontend
    displayName: 'Sonar Analysis for Frontend'
    dependsOn: Build
    jobs:
      - job: sonarqube_analysis_Frontend
        steps:
          - task: SonarQubePrepare@7
            inputs:
              SonarQube: 'sonarqube_svc'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'devops_frontend'
              cliProjectName: 'devops_frontend'
              cliSources: './frontend'
          - task: SonarQubeAnalyze@7
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'

  - stage: SonarQube_Backend
    displayName: 'Sonar Analysis for Backend'
    dependsOn: Build
    jobs:
      - job: sonarqube_analysis_Backend
        steps:
          - task: SonarQubePrepare@7
            inputs:
              SonarQube: 'sonarqube_svc'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'devops_backend'
              cliProjectName: 'devops_backend'
              cliSources: './backend'
          - task: SonarQubeAnalyze@7
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'

# Docker build and push stages
  - stage: Docker_Build_push_backend
    displayName: 'Docker Build and Push Backend'
    dependsOn: 
      - Trivy_FS_Scan
      - SonarQube_Backend
    jobs:
      - job: docker_build_push
        displayName: 'Docker Build and Push Backend'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-svc'
              repository: 'react_backend'
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              tags: 'latest'

  - stage: Docker_Build_push_frontend
    displayName: 'Docker Build and Push Frontend'
    dependsOn: 
      - Trivy_FS_Scan
      - SonarQube_Frontend
    jobs:
      - job: docker_build_push
        displayName: 'Docker Build and Push Frontend'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-svc'
              repository: 'react_frontend'
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'
              tags: 'latest'

# AKS deployment stage
  - stage: deploy_to_aks
    displayName: 'Deploy to AKS'
    dependsOn:
      - Docker_Build_push_backend
      - Docker_Build_push_frontend
    jobs:
      - job: deploy_to_aks
        displayName: 'Deploy to AKS'
        steps:
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'aks-svc'
              namespace: 'default'
              manifests: 'k8s/*.yaml'