trigger:
  - main

pool:
  name: mi-selfhost

stages:
  - stage: Build
    jobs:
      - job: frontend_build
        displayName: 'Build Frontend'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'
            displayName: 'Install Node.js'

          - script: |
              rm -f frontend/.npmrc backend/.npmrc .npmrc ~/.npmrc
              rm -f frontend/package-lock.json backend/package-lock.json
              npm cache clean --force
              rm -rf ~/.npm
              npm config set registry https://registry.npmjs.org/
              npm config set audit false
              echo "registry=https://registry.npmjs.org/" > frontend/.npmrc
              echo "audit=false" >> frontend/.npmrc
              echo "registry=https://registry.npmjs.org/" > backend/.npmrc
              echo "audit=false" >> backend/.npmrc
            displayName: 'Clean npm Configuration'

          - script: |
              cd frontend
              npm install --no-audit --no-fund --loglevel=error
            displayName: 'Install Frontend Dependencies'
            timeoutInMinutes: 15

          - script: |
              cd frontend
              npm run build
            displayName: 'Build Frontend'
            timeoutInMinutes: 10

      - job: backend_build
        displayName: 'Build Backend'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'
            displayName: 'Install Node.js'

          - script: |
              rm -f frontend/.npmrc backend/.npmrc .npmrc ~/.npmrc
              rm -f frontend/package-lock.json backend/package-lock.json
              npm cache clean --force
              rm -rf ~/.npm
              npm config set registry https://registry.npmjs.org/
              npm config set audit false
              echo "registry=https://registry.npmjs.org/" > frontend/.npmrc
              echo "audit=false" >> frontend/.npmrc
              echo "registry=https://registry.npmjs.org/" > backend/.npmrc
              echo "audit=false" >> backend/.npmrc
            displayName: 'Clean npm Configuration'

          - script: |
              cd backend
              npm install --no-audit --no-fund --loglevel=error
            displayName: 'Install Backend Dependencies'
            timeoutInMinutes: 15

          - script: |
              cd backend
              if npm run | grep -q "build"; then
                npm run build
              else
                echo "No build script found, skipping build step"
              fi
            displayName: 'Build Backend (if applicable)'
            timeoutInMinutes: 10
            continueOnError: true

  - stage: SonarQube_Analysis
    displayName: 'SonarQube Code Analysis'
    dependsOn: Build
    jobs:
      - job: sonarqube_frontend
        displayName: 'SonarQube Frontend Analysis'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'
            displayName: 'Install Node.js'

          # Reinstall dependencies for SonarQube analysis
          - script: |
              npm config set registry https://registry.npmjs.org/
              npm config set audit false
              cd frontend
              npm install --no-audit --no-fund --loglevel=error
            displayName: 'Install Frontend Dependencies'
            continueOnError: true

          - task: SonarQubePrepare@7
            inputs:
              SonarQube: 'sonarqube_svc'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'devops_frontend'
              cliProjectName: 'devops_frontend'
              cliSources: './frontend'
              extraProperties: |
                sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**
                sonar.javascript.lcov.reportPaths=coverage/lcov.info

          - task: SonarQubeAnalyze@7
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'
            continueOnError: true

          - task: SonarQubePublish@7
            inputs:
              pollingTimeoutSec: '300'
            continueOnError: true

      - job: sonarqube_backend
        displayName: 'SonarQube Backend Analysis'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'
            displayName: 'Install Node.js'

          # Reinstall dependencies for SonarQube analysis
          - script: |
              npm config set registry https://registry.npmjs.org/
              npm config set audit false
              cd backend
              npm install --no-audit --no-fund --loglevel=error
            displayName: 'Install Backend Dependencies'
            continueOnError: true

          - task: SonarQubePrepare@7
            inputs:
              SonarQube: 'sonarqube_svc'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'devops_backend'
              cliProjectName: 'devops_backend'
              cliSources: './backend'
              extraProperties: |
                sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**

          - task: SonarQubeAnalyze@7
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'
            continueOnError: true

          - task: SonarQubePublish@7
            inputs:
              pollingTimeoutSec: '300'
            continueOnError: true

  - stage: Trivy_FS_Scan
    displayName: 'Trivy FS Scan Frontend & Backend'
    dependsOn: Build
    jobs:
      - job: trivy_fs_scan_frontend
        displayName: 'Trivy FS Scan Frontend'
        steps:
          - script: |
              cd frontend
              trivy fs --format table -o trivy-frontend.html .
            displayName: 'Trivy Scan Frontend'
          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: 'frontend-report'
              targetPath: 'frontend/trivy-frontend.html'

      - job: trivy_fs_scan_backend
        displayName: 'Trivy FS Scan Backend'
        steps:
          - script: |
              cd backend
              trivy fs --format table -o trivy-backend.html .
            displayName: 'Trivy Scan Backend'
          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: 'backend-report'
              targetPath: 'backend/trivy-backend.html'

  - stage: Docker_Build_push_backend
    displayName: 'Docker Build and Push Backend'
    dependsOn: 
      - Trivy_FS_Scan
      - SonarQube_Analysis
    jobs:
      - job: docker_build_push
        displayName: 'Docker Build and Push Backend'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-svc'
              repository: 'react_backend'
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              tags: 'latest'

  - stage: Docker_Build_push_frontend
    displayName: 'Docker Build and Push Frontend'
    dependsOn: 
      - Trivy_FS_Scan
      - SonarQube_Analysis
    jobs:
      - job: docker_build_push
        displayName: 'Docker Build and Push Frontend'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-svc'
              repository: 'react_frontend'
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'
              tags: 'latest'

  - stage: deploy_to_aks
    displayName: 'Deploy to AKS'
    dependsOn:
      - Docker_Build_push_backend
      - Docker_Build_push_frontend
    jobs:
      - job: deploy_to_aks
        displayName: 'Deploy to AKS'
        steps:
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'aks-svc'
              namespace: 'default'
              manifests: 'k8s/*.yaml'